# fly.toml app configuration file generated for emoji-story on 2023-10-31T14:20:57+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "emoji-story"
primary_region = "cdg"

[http_service]
  internal_port = 4000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]


# [[services]]
#   internal_port = 4000
#   protocol = "tcp"

#   [services.concurrency]
#     hard_limit = 25
#     soft_limit = 20

#   [[services.ports]]
#     handlers = ["http"]
#     port = "80"

#   [[services.ports]]
#     handlers = ["tls", "http"]
#     port = "443"

#   [[services.tcp_checks]]
#     interval = 10000
#     timeout = 2000

[build]
  dockerfile = "./server/Dockerfile"
  ignorefile = "./server/.dockerignore"