name: Fly Deploy Front
on:
  push:
    branches:
      - main
    paths: 
      - 'front/**'

  workflow_dispatch: 
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config fly.front.tml 
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
