name: Fly Deploy Server
on:
  push:
    branches:
      - main
    paths:
      - "server/**"

  workflow_dispatch: 

jobs:
  deploy:
    name: Deploy server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --ha=false --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
